export const products = [
	{
		id: "1",
		unique_id: "NODX8N4Y8K3U4T",
		restaurant_id: "0",
		name: "Full Thali + Rabdi(100Gm)",
		title: "",
		description: "",
		product_description:
			'Rabri (IAST: Rabaḍī) is a sweet, condensed-milk-based dish, originating from the Indian ... "Full text of "Indian Food Tradition A Historical Companion Achaya K',
		discount_allowed: "0",
		views: "0",
		feetured_product: "0",
		special_product: "0",
		date: "2021-02-10 01:05:53",
		product_type: "0",
		egg_included: "0",
		coupon_code_allowed: "0",
		quantity: "0",
		price: "0",
		img: "405ea2c2a60f9036f2fd3f794f1e4b4f.jpeg",
		image_path: "uploads/restaurant/NODM8K5D2S1E4L/NODX8N4Y8K3U4T",
		multiple_img: "",
		url: "full-thali-+-rabdi100gm",
		category_id: "5",
		subcategory_id: "10",
		childcategory_id: "0",
		created_by: "NODM8K5D2S1E4L",
		status: "1",
		deleted: "0",
	},
	{
		id: "2",
		unique_id: "NODZ2E2L3A2T8Z",
		restaurant_id: "0",
		name: "Veg Manchurian",
		title: "",
		description: "",
		product_description:
			"For fried veg manchurian balls. ½ cup grated or finely chopped cabbage (green or red cabbage) ½ cup grated carrot. ¼ cup finely chopped capsicum (green bell",
		discount_allowed: "0",
		views: "0",
		feetured_product: "0",
		special_product: "0",
		date: "2021-02-10 01:08:31",
		product_type: "0",
		egg_included: "0",
		coupon_code_allowed: "0",
		quantity: "0",
		price: "0",
		img: "a09400cd0b95b051a6a20d5bbd38aab7.jpeg",
		image_path: "uploads/restaurant/NODM8K5D2S1E4L/NODZ2E2L3A2T8Z",
		multiple_img: "",
		url: "veg-manchurian",
		category_id: "1",
		subcategory_id: "1",
		childcategory_id: "0",
		created_by: "NODM8K5D2S1E4L",
		status: "1",
		deleted: "0",
	},
	{
		id: "3",
		unique_id: "NODF1P1D9L3G1K",
		restaurant_id: "0",
		name: "Idli",
		title: "",
		description: "",
		product_description:
			"Idli is a soft & fluffy steamed cake made of fermented rice & lentil batter. These are one of the healthiest protein packed Breakfasts from South Indian cuis",
		discount_allowed: "0",
		views: "0",
		feetured_product: "0",
		special_product: "0",
		date: "2021-02-13 03:14:35",
		product_type: "0",
		egg_included: "0",
		coupon_code_allowed: "1",
		quantity: "0",
		price: "0",
		img: "6c60d6d04b56a850830cbf729df8bbd9.jpg",
		image_path: "uploads/restaurant/NODM8K5D2S1E4L/NODF1P1D9L3G1K",
		multiple_img: "",
		url: "idli",
		category_id: "2",
		subcategory_id: "0",
		childcategory_id: "0",
		created_by: "NODM8K5D2S1E4L",
		status: "1",
		deleted: "0",
	},
	{
		id: "4",
		unique_id: "NODT8Z0V6W1S1E",
		restaurant_id: "0",
		name: "Rava Masala Dosa",
		title: "",
		description: "",
		product_description:
			"rava masala dosa recipe is a famous south indian crepe prepared with rava or semolina. this very similar to rava onion dosa recipe, however aloo bhaji is topp",
		discount_allowed: "0",
		views: "0",
		feetured_product: "0",
		special_product: "0",
		date: "2021-02-10 01:13:29",
		product_type: "0",
		egg_included: "0",
		coupon_code_allowed: "0",
		quantity: "0",
		price: "0",
		img: "6329e9080f0fc1a94f3751726fdf2778.jpg",
		image_path: "uploads/restaurant/NODM8K5D2S1E4L/NODT8Z0V6W1S1E",
		multiple_img: "",
		url: "rava-masala-dosa",
		category_id: "2",
		subcategory_id: "4",
		childcategory_id: "0",
		created_by: "NODM8K5D2S1E4L",
		status: "1",
		deleted: "0",
	},
	{
		id: "5",
		unique_id: "NODS6T8K0Q2E3Y",
		restaurant_id: "0",
		name: "Rawa Plain Dosa",
		title: "",
		description: "",
		product_description:
			"Rava dosa is a South Indian breakfast made with semolina, cumin, ginger, coriander leaves and green chilies. These aromatic crisp toasted thin ...",
		discount_allowed: "0",
		views: "0",
		feetured_product: "0",
		special_product: "0",
		date: "2021-02-10 01:15:04",
		product_type: "0",
		egg_included: "0",
		coupon_code_allowed: "0",
		quantity: "0",
		price: "0",
		img: "b9bd16683fc567bd243d31f98bc3c720.jpg",
		image_path: "uploads/restaurant/NODM8K5D2S1E4L/NODS6T8K0Q2E3Y",
		multiple_img: "",
		url: "rawa-plain-dosa",
		category_id: "2",
		subcategory_id: "4",
		childcategory_id: "0",
		created_by: "NODM8K5D2S1E4L",
		status: "1",
		deleted: "0",
	},
	{
		id: "6",
		unique_id: "NODU6U2I7S7V7K",
		restaurant_id: "0",
		name: "Uttapam",
		title: "",
		description: "",
		product_description:
			"Uttapam are South Indian Breakfast pancakes made with lentils, rice, onions, herbs & spices. These are a very common breakfast in south Indian homes and are m",
		discount_allowed: "0",
		views: "0",
		feetured_product: "0",
		special_product: "0",
		date: "2021-02-10 01:16:26",
		product_type: "0",
		egg_included: "0",
		coupon_code_allowed: "0",
		quantity: "0",
		price: "0",
		img: "eaf267f4e3340e096ef461b68def0fa5.jpg",
		image_path: "uploads/restaurant/NODM8K5D2S1E4L/NODU6U2I7S7V7K",
		multiple_img: "",
		url: "uttapam",
		category_id: "2",
		subcategory_id: "5",
		childcategory_id: "0",
		created_by: "NODM8K5D2S1E4L",
		status: "1",
		deleted: "0",
	},
	{
		id: "7",
		unique_id: "NODR1I7C9H5T6Q",
		restaurant_id: "0",
		name: "Pav Bhaji",
		title: "",
		description: "",
		product_description:
			"Pav Bhaji is a spicy mashed vegetable dish, served piping hot with a dollop of butter, diced red onions, cilantro, and a squeeze of lime.",
		discount_allowed: "0",
		views: "0",
		feetured_product: "0",
		special_product: "0",
		date: "2021-02-10 01:18:01",
		product_type: "0",
		egg_included: "0",
		coupon_code_allowed: "0",
		quantity: "0",
		price: "0",
		img: "713a8ff8a0069bc0746b8adec50618a5.jpg",
		image_path: "uploads/restaurant/NODM8K5D2S1E4L/NODR1I7C9H5T6Q",
		multiple_img: "",
		url: "pav-bhaji",
		category_id: "3",
		subcategory_id: "6",
		childcategory_id: "0",
		created_by: "NODM8K5D2S1E4L",
		status: "1",
		deleted: "0",
	},
	{
		id: "8",
		unique_id: "NODR8I2G2V9Q0A",
		restaurant_id: "0",
		name: "Veg Sandwich",
		title: "",
		description: "",
		product_description:
			"For grilling in veg sandwich in toaster – Butter the bread slices on the outer side. On the inner side spread the veggie mix and cover with another slice. Gril",
		discount_allowed: "1",
		views: "0",
		feetured_product: "0",
		special_product: "0",
		date: "2021-02-10 07:55:52",
		product_type: "0",
		egg_included: "0",
		coupon_code_allowed: "1",
		quantity: "0",
		price: "0",
		img: "f029c408e44314ae6a00f578ec534dcc.jpeg",
		image_path: "uploads/restaurant/NODM8K5D2S1E4L/NODR8I2G2V9Q0A",
		multiple_img: 'a:1:{i:0;s:37:"50f76fb537c7095ff943fd6d588a0f13.jpeg";}',
		url: "veg-sandwich",
		category_id: "3",
		subcategory_id: "7",
		childcategory_id: "0",
		created_by: "NODM8K5D2S1E4L",
		status: "1",
		deleted: "0",
	},
	{
		id: "9",
		unique_id: "NODC2Z5Y3M6N2P",
		restaurant_id: "0",
		name: "Veg Pizza",
		title: "",
		description: "",
		product_description:
			"Veg pizzas · Margherita · Double Cheese Margherita · Farm House · Peppy Paneer · Mexican Green Wave · Deluxe Veggie · Veg Extravaganza · CHEESE N CORN.",
		discount_allowed: "0",
		views: "0",
		feetured_product: "0",
		special_product: "0",
		date: "2021-02-10 01:22:11",
		product_type: "0",
		egg_included: "0",
		coupon_code_allowed: "0",
		quantity: "0",
		price: "0",
		img: "dc67f98ca961ec35bd82005aeb297d3b.jpeg",
		image_path: "uploads/restaurant/NODM8K5D2S1E4L/NODC2Z5Y3M6N2P",
		multiple_img: "",
		url: "veg-pizza",
		category_id: "4",
		subcategory_id: "0",
		childcategory_id: "0",
		created_by: "NODM8K5D2S1E4L",
		status: "1",
		deleted: "0",
	},
];
export const productCategory = [
	{
		id: "1",
		unique_id: "NODE4I3S4S9P3O",
		name: "Starter",
		title: "Starter products",
		keyword: "restaurant Starter items",
		description:
			"restaurant Starter items like Manchurian cold drinks and all",
		url: "starter",
		img: "3c19173784a56613fb0764dfcb841ea6.jpg",
		status: "0",
		date: "2021-02-10 04:44:51",
		deleted: "0",
	},
	{
		id: "2",
		unique_id: "NODM6Q0V8L1I8T",
		name: "South Indian",
		title: "South Indian items",
		keyword: "South Indian items idli Masala Dosa.",
		description:
			"South Indian items like  idli Masala Dosa.Chicken Stew with Appams. .",
		url: "south-indian",
		img: "51944a442c8b7c630c5e5277466a5274.jpeg",
		status: "1",
		date: "2021-02-10 04:50:34",
		deleted: "0",
	},
	{
		id: "3",
		unique_id: "NODX9O2R7Z5D5V",
		name: "Quick Bites",
		title: "Quick Bites items",
		keyword: "Quick Bites items",
		description:
			"Imagine this: You've been attacked by sudden hunger only to be left staring at empty refrigerator shelves and kitchen cabinets. Now, that's the time you might",
		url: "quick-bites",
		img: "beb4d953b6d0a35c2dbca201bc0ac32b.jpeg",
		status: "1",
		date: "2021-02-10 04:52:45",
		deleted: "0",
	},
	{
		id: "4",
		unique_id: "NODL9A7E1N4R8I",
		name: "Pizzas",
		title: "Happiness that comes packed in a box; it's got to be a pizza!",
		keyword:
			"Happiness that comes packed in a box; it's got to be a pizza!",
		description:
			"How can you not fall for the crispy crusts coupled with an exciting play of ingredients with gooey cheese atop? Pizzas are one of the most popular food items",
		url: "pizzas",
		img: "79cf308b9df27ff59b4d2468f2362b60.jpeg",
		status: "1",
		date: "2021-02-10 04:55:02",
		deleted: "0",
	},
	{
		id: "5",
		unique_id: "NODA1T9K1O2O7E",
		name: "Main Course",
		title:
			"Hundreds of main dish recipes. Choose from top-rated comfort food, hea",
		keyword: "while also being easy and delic",
		description:
			"Come by for dinner! I'm making...what, exactly? If you're having people over, you want dinner party recipes that feel special (while also being easy and delic",
		url: "main-course",
		img: "9bfab163024e5f27d802a717b0a531c5.jpg",
		status: "1",
		date: "2021-02-10 04:57:12",
		deleted: "0",
	},
	{
		id: "6",
		unique_id: "NODK2T5B6O5Q9J",
		name: "Thalis",
		title:
			"Thalis are the best way to enjoy a sumptuous Indian meal with variety",
		keyword:
			"Thalis are the best way to enjoy a sumptuous Indian meal with variety in flavour and types of foods. You pay a price and then it's an all-you-can-eat bonanza as you are served rice, pooris, phulkas, dals, curries, and various kinds of dessert.",
		description:
			"Thalis are the best way to enjoy a sumptuous Indian meal with variety in flavour and types of foods. You pay a price and then it's an all-you-can-eat bonanza",
		url: "thali",
		img: "b56f1dc3cc77d2fd36b68a63317a0a5a.jpg",
		status: "1",
		date: "2021-02-10 04:59:27",
		deleted: "0",
	},
	{
		id: "7",
		unique_id: "NODH0S8C5R1Q9I",
		name: "Desserts",
		title:
			"urn any night into a special occasion with our simple recipes for rest",
		keyword:
			"urn any night into a special occasion with our simple recipes for restaurant favorites like molten lava cake, creme brulee and strawberry shortcake. No reservations required!",
		description:
			"urn any night into a special occasion with our simple recipes for restaurant favorites like molten lava cake, creme brulee and strawberry shortcake. No reserv",
		url: "desserts",
		img: "c30a5787a34c455f272dfb3b3cdf7d07.png",
		status: "1",
		date: "2021-02-10 05:02:13",
		deleted: "0",
	},
	{
		id: "8",
		unique_id: "NODZ6E9O1F6L4S",
		name: "Breakfast",
		title: "Indian Breakfast Recipes",
		keyword: "Indian Breakfast Recipes",
		description:
			"We all know breakfast is the most important meal of the day. But just because you're aware that this meal is crucial doesn't mean you always have time to whip",
		url: "breakfast",
		img: "feef05c74fa7d42c45f83b640dbb3e7f.jpg",
		status: "1",
		date: "2021-02-10 05:13:42",
		deleted: "0",
	},
	{
		id: "9",
		unique_id: "NODM6G7M8O4Y1T",
		name: "Beverages",
		title:
			"Beverage is any liquid consumed by humans for quenching thirst, or mer",
		keyword:
			"Beverage is any liquid consumed by humans for quenching thirst, or merely for pleasure. Beverages come in various types −",
		description:
			"Beverage is any liquid consumed by humans for quenching thirst, or merely for pleasure. Beverages come in various types −",
		url: "beverages",
		img: "0fbaba795ed76ed91eb3662e4ba2cd04.jpg",
		status: "1",
		date: "2021-02-10 05:20:13",
		deleted: "0",
	},
	{
		id: "10",
		unique_id: "NODC9Q3S0C2J8O",
		name: "Extras",
		title: "Extras items in restaurants",
		keyword: "Extras items in restaurants like curd",
		description:
			"Restaurant Menu is a convenient extra to show your assortment of meals and beverages. You can select numerous number of menus with a amazing amount items. Don",
		url: "extras",
		img: "0f6adea3ba130699d881d0b06e98db96.png",
		status: "1",
		date: "2021-02-10 05:28:28",
		deleted: "0",
	},
	{
		id: "11",
		unique_id: "NODV5N9O7R7Z5N",
		name: "Indian Breads",
		title: "Indian Breads Roti",
		keyword: "Indian Breads like Roti chapati tandur",
		description:
			"Indian Breads like Roti chapati tandurIndian Breads like Roti chapati tandur",
		url: "indian-breads",
		img: "36562ab5f73755e05118ee76e73bd641.jpg",
		status: "1",
		date: "2021-02-10 05:34:27",
		deleted: "0",
	},
];
export const productStock = [
	{
		id: "1",
		name: "Starter",
		quantity: "10",
	},
	{
		id: "2",
		name: "South Indian",
		quantity: "30",
	},
	{
		id: "3",
		name: "Quick Bites",
		quantity: "20",
	},
	{
		id: "4",
		name: "Pizzas",
		quantity: "30",
	},
	{
		id: "5",
		name: "Main Course",
		quantity: "20",
	},
	{
		id: "6",
		name: "Thalis",
		quantity: "40",
	},
	{
		id: "7",
		name: "Desserts",
		quantity: "8",
	},
	{
		id: "8",
		name: "Breakfast",
		quantity: "8",
	},
	{
		id: "9",
		name: "Beverages",
		quantity: "99",
	},
	{
		id: "10",
		name: "Extras",
		quantity: "67",
	},
	{
		id: "11",
		name: "Indian Breads",
		quantity: "2",
	},
];
export const restaurantList = [
	{
		id: "1",
		unique_id: "NODM8K5D2S1E4L",
		rest_cat_id: "4",
		name: "The Book Cafè",
		url: "the-book-caf",
		title: "COFFEE IS ALWAYS A GOOD IDEA",
		keyword: "",
		phone: "9929383588",
		email: "thebookcafe@gmail.com",
		date: "2021-02-10 12:50:11",
		qr_code: "ixRW8mHV8grm",
		qr_img: "uploads/restaurant/NODM8K5D2S1E4L/6038c34ed3f85.png",
		country: "1",
		state: "1",
		city: "8",
		address:
			"Cyber Park Plot No Cyb - 5 Dream Heights, Heavy Industrial Area, Near Jodhpur Saras Dairy, Near Anand Rathi, Jodhpur 342003 India",
		pincode: "342001",
		description:
			"Building Cafe culture and bringing together creative people over a coffee. The theme of The Book Cafe is to develop a culture where people connect to grow and",
		img: "7061877e6541d3321f937532cc640eb6.jpeg",
		logo: "7061877e6541d3321f937532cc640eb6.jpeg",
		online_booking: "1",
		online_table_booking: "1",
		take_away: "1",
		shipping_charge: "0",
		shipping_amt: "20",
		shipp_reason: "any condition",
		disc_amt: "10",
		disc_reason: "any condition",
		adv_support: "1",
		spc_discount: "0",
		min_booking: "100",
		opentime: "08:53:00",
		closetime: "20:59:00",
		status: "1",
		deleted: "0",
		created_by: "0",
	},
	{
		id: "2",
		unique_id: "NODE6J5F7Y6Y2U",
		rest_cat_id: "1",
		name: "Auntys Pizza",
		url: "auntys-pizza",
		title: "Plenty of Vegetarian Options,",
		keyword: "",
		phone: "8387867538",
		email: "ajayssdfshara0n211@gmail.com",
		date: "2021-02-10 12:57:51",
		qr_code: "FTq9P4enZTnC",
		qr_img: "uploads/restaurant/NODE6J5F7Y6Y2U/603733b462c87.png",
		country: "1",
		state: "1",
		city: "8",
		address: "Shop B-14, Shastri Circle, Shastri Nagar, Jodhpur",
		pincode: "342001",
		description:
			"Plenty of Vegetarian Options, Good Crowd, Inexpensive, Great Recommendations, Prompt Service, Amazing Food",
		img: "51733cf4517d03422e455fb163b01f5f.jpeg",
		logo: "51733cf4517d03422e455fb163b01f5f.jpeg",
		online_booking: "0",
		online_table_booking: "0",
		take_away: "0",
		shipping_charge: "0",
		shipping_amt: "0",
		shipp_reason: "",
		disc_amt: "0",
		disc_reason: "",
		adv_support: "0",
		spc_discount: "0",
		min_booking: "0",
		opentime: "00:00:00",
		closetime: "00:00:00",
		status: "1",
		deleted: "0",
		created_by: "0",
	},
	{
		id: "3",
		unique_id: "NODL6D1M7H4K0K",
		rest_cat_id: "0",
		name: "Kalinga Restaurant",
		url: "kalinga-restaurant",
		title: "WE ARE FRESHSHOP",
		keyword: "",
		phone: "2912615871",
		email: "kalinga@gmail.com",
		date: "2021-02-23 05:51:15",
		qr_code: "LkNlzys9Y23b",
		qr_img: "uploads/restaurant/NODL6D1M7H4K0K/6034f355e63ba.png",
		country: "1",
		state: "1",
		city: "8",
		address: "Near Railway Station, Jodhpur-1, Jodhpur, Rajasthan,",
		pincode: "342001",
		description: "291-2615871291-2615871291-2615871291-2615871291-2615871",
		img: "bf048265edef1e674d858b63c8a7d764.jpg",
		logo: "bf048265edef1e674d858b63c8a7d764.jpg",
		online_booking: "0",
		online_table_booking: "0",
		take_away: "0",
		shipping_charge: "0",
		shipping_amt: "0",
		shipp_reason: "",
		disc_amt: "0",
		disc_reason: "",
		adv_support: "0",
		spc_discount: "0",
		min_booking: "0",
		opentime: "00:00:00",
		closetime: "00:00:00",
		status: "1",
		deleted: "0",
		created_by: "0",
	},
];
