export const FETCH_USER_REQUEST = '/user/FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = '/user/FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = '/user/FETCH_USER_FAILURE'

export const SET_USER_DATA = '/user/SET_USER_DATA'
export const CLEAR_USER_DATA = '/user/CLEAR_USER_DATA'

export const FETCH_USER_ADDRESS_REQUEST = '/user/FETCH_USER_ADDRESS_REQUEST'
export const FETCH_USER_ADDRESS_SUCCESS = '/user/FETCH_USER_ADDRESS_SUCCESS'
export const FETCH_USER_ADDRESS_FAILURE = '/user/FETCH_USER_ADDRESS_FAILURE'

export const NEW_ADDRESS_REQUEST = '/user/NEW_ADDRESS_REQUEST'
export const NEW_ADDRESS_SUCCESS = '/user/NEW_ADDRESS_SUCCESS'
export const NEW_ADDRESS_FAILURE = '/user/NEW_ADDRESS_FAILURE'
